CREATE TABLE IF NOT EXISTS `tbl_revenue_config` (
  `id` BIGINT NOT NULL,
  `tax_code_id` VARCHAR(50) NOT NULL,
  `tax_code_description` VARCHAR(255) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `responsible_ministry_id` BIGINT NOT NULL,
  `third_party_provider_id` BIGINT DEFAULT NULL,
  `gol_percentage` DECIMAL(5,2) NOT NULL,
  `ministry_percentage` DECIMAL(5,2) NOT NULL,
  `third_party_percentage` DECIMAL(5,2) NOT NULL,
  `sending_dfsp_percentage` DECIMAL(5,2) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `created_date` BIGINT DEFAULT NULL,
  `updated_date` BIGINT DEFAULT NULL,
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_tbl_revenue_config_tax_code_id` (`tax_code_id`),
  KEY `idx_tbl_revenue_config_status` (`status`),
  KEY `idx_tbl_revenue_config_responsible_ministry_id` (`responsible_ministry_id`),
  KEY `idx_tbl_revenue_config_third_party_provider_id` (`third_party_provider_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tbl_revenue_config_history` (
  `history_id` BIGINT NOT NULL,
  `revenue_config_id` BIGINT NOT NULL,
  `tax_code_id` VARCHAR(50) NOT NULL,
  `tax_code_description` VARCHAR(255) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `responsible_ministry_id` BIGINT NOT NULL,
  `third_party_provider_id` BIGINT DEFAULT NULL,
  `gol_percentage` DECIMAL(5,2) NOT NULL,
  `ministry_percentage` DECIMAL(5,2) NOT NULL,
  `third_party_percentage` DECIMAL(5,2) NOT NULL,
  `sending_dfsp_percentage` DECIMAL(5,2) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `created_date` BIGINT DEFAULT NULL,
  `updated_date` BIGINT DEFAULT NULL,
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  PRIMARY KEY (`history_id`),
  KEY `idx_tbl_revenue_config_history_config_id` (`revenue_config_id`),
  CONSTRAINT `fk_tbl_revenue_config_history_config_id`
    FOREIGN KEY (`revenue_config_id`) REFERENCES `tbl_revenue_config` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
